#!/usr/bin/env bash
dir='ex/cmd/gnuplot-out/b244d71427e1cb62194f7236fb1e96c6'
cp -p ex/data/*.* "$dir"
export CX_RANDOM_SEED=1638854222
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_VERBOSE" ]] && set -x
(
  cx in plot.csv // -h // gnuplot- --size=80x25 // cmd gnuplot;
  echo $! > exit_code
) 2> stderr > actual
[[ -f expected ]] || cp actual expected
diff -u expected actual | (read _; read _; cat) > diff
[[ ! -s diff ]]
