#!/usr/bin/env bash
dir='ex/cmd/reverse/4cba25f0f1ad715532f7cbd52bd3230d'
cp -p ex/data/*.* "$dir"
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_VERBOSE" ]] && set -x
(
  cx in SOME.cxv // -h // reverse // h-
) >actual
echo $! > exit
[[ -f expected ]] || cp actual expected
diff -u expected actual > diff
[[ ! -s diff ]]
