#!/usr/bin/env bash
dir='ex/cmd/stats/2c4b4d4361e1bd906e8a2e1d630c0d0e'
cp -p ex/data/*.* "$dir"
export CX_RANDOM_SEED=1638854222
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_VERBOSE" ]] && set -x
(
  cx in stats-data.csv // -h // parse // stats dept:g job:g salary // md;
  echo $! > exit_code
) 2> stderr > actual
[[ -f expected ]] || cp actual expected
diff -u expected actual | (read _; read _; cat) > diff
[[ ! -s diff ]]
