#!/usr/bin/env bash
dir='ex/cmd/meta-set/7dcb83f6662582c44ea026c0b8d5ce57'
cp -p ex/data/*.* "$dir"
export CX_RANDOM_SEED=1638854222
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_EX_VERBOSE" ]] && set -x
cx in SOME.csv // -h // -meta // meta-set 'a:max_size=20;align=right' // md 2> stderr > actual
echo $! > exit_code
[[ -f expected ]] || cp actual expected
diff -u expected actual | (read _; read _; cat) > diff
[[ ! -s diff ]]
