#!/usr/bin/env bash
dir='ex/cmd/csv-out/0dedd8eff3d0f13183aa3e97061627c2'
cp -p ex/data/*.* "$dir"
export CX_RANDOM_SEED=1638854222
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_VERBOSE" ]] && set -x
(
  cx in SOME.csv // csv- --separator="\x09"
) >actual
echo $! > exit
[[ -f expected ]] || cp actual expected
diff -u expected actual | (read _; read _; cat) > diff
[[ ! -s diff ]]
