#!/usr/bin/env bash
dir='ex/cmd/markdown-out/3e558e04bebf7a0eb41c33969389bd4a'
cp -p ex/data/*.* "$dir"
export CX_RANDOM_SEED=1638854222
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_EX_VERBOSE" ]] && set -x
cx in SOME.csv // -h // parse // md 2> stderr > actual
echo $! > exit_code
[[ -f expected ]] || cp actual expected
diff -u expected actual | (read _; read _; cat) > diff
[[ ! -s diff ]]
