#!/usr/bin/env bash
dir='ex/cmd/cut/f88433c7cfe98f7bea9bef27948aa374'
cp -p ex/data/*.* "$dir"
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_VERBOSE" ]] && set -x
(
  cx in SOME.csv // -h // cut d,@
) >actual
echo $! > exit
[[ -f expected ]] || cp actual expected
diff -u expected actual > diff
[[ ! -s diff ]]
