#!/usr/bin/env bash
dir='ex/cmd/cut/1787b086601757a79c77b266221e7c47'
cp -p ex/data/*.* "$dir"
cd "$dir" || exit 9
set -x
(
  cx in SOME.csv // -h // cut a,d    // h-
) >actual
echo $! > exit
[[ -f expected ]] || cp actual expected
diff -u expected actual | tee diff
[[ ! -s diff ]]
