#!/usr/bin/env bash
dir='ex/cmd/markdown-out/b1a4d5a88ee8fec939c40c917812c583'
cp -p ex/data/*.* "$dir"
export CX_RANDOM_SEED=1638854222
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_VERBOSE" ]] && set -x
(
  cx in SOME.csv // -h // parse // markdown
) >actual
echo $! > exit
[[ -f expected ]] || cp actual expected
diff -u expected actual > diff
[[ ! -s diff ]]
