#!/usr/bin/env bash
dir='ex/cmd/header-out/f25a386c134e5a85a2027cf0e27d7b86'
cp -p ex/data/*.* "$dir"
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_VERBOSE" ]] && set -x
(
  cx in SOME.csv // -csv // -h // h- // csv-
) >actual
echo $! > exit
[[ -f expected ]] || cp actual expected
diff -u expected actual > diff
[[ ! -s diff ]]
