#!/usr/bin/env bash
dir='ex/cmd/header-in/c1d5d981396b5382db858a9c5c7443a6'
cp -p ex/data/*.* "$dir"
export CX_RANDOM_SEED=1638854222
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_VERBOSE" ]] && set -x
(
  cx in SOME.csv // -csv // -h // csv-;
  echo $! > exit
) 2> stderr > actual
[[ -f expected ]] || cp actual expected
diff -u expected actual | (read _; read _; cat) > diff
[[ ! -s diff ]]
