#!/usr/bin/env bash
dir='ex/cmd/cat/8231f0faf86e2e13e3ced05a13e215a8'
cp -p ex/data/*.* "$dir"
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_VERBOSE" ]] && set -x
(
  cx in OTHER.csv // -h // cat {{ cx in DUPLICATES // -h }} // h-
) >actual
echo $! > exit
[[ -f expected ]] || cp actual expected
diff -u expected actual > diff
[[ ! -s diff ]]
