#!/usr/bin/env bash
dir='ex/cmd/tsv-out/601ff75386510559125b1a5d587078f1'
cp -p ex/data/*.* "$dir"
export CX_RANDOM_SEED=1638854222
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_EX_VERBOSE" ]] && set -x
cx in SOME.csv // tsv- 2> stderr > actual
echo $! > exit_code
[[ -f expected ]] || cp actual expected
diff -u expected actual | (read _; read _; cat) > diff
[[ ! -s diff ]]
