#!/usr/bin/env bash
dir='ex/cmd/replace/c58cbd8fd209e95740011cb4db45f1b6'
cp -p ex/data/*.* "$dir"
export CX_RANDOM_SEED=1638854222
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_EX_VERBOSE" ]] && set -x
cx in RANDOM.csv // -h // region 1..5 // replace --search=1 --replace= --global // h- 2> stderr > actual
echo $! > exit_code
[[ -f expected ]] || cp actual expected
diff -u expected actual | (read _; read _; cat) > diff
[[ ! -s diff ]]
