#!/usr/bin/env bash
dir='ex/cmd/meta-set/0ee6bd60506f3e5cc569e0b4a595659e'
cp -p ex/data/*.* "$dir"
export CX_RANDOM_SEED=1638854222
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_EX_VERBOSE" ]] && set -x
cx in SOME.csv // -h // -meta // meta= 'c:some_option=123' // meta- // md 2> stderr > actual
echo $! > exit_code
[[ -f expected ]] || cp actual expected
diff -u expected actual | (read _; read _; cat) > diff
[[ ! -s diff ]]
