#!/usr/bin/env bash
dir='ex/cmd/stats/2a6d2abcb7a1a4dc549a2d54ffdd12dd'
cp -p ex/data/*.* "$dir"
export CX_RANDOM_SEED=1638854222
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_VERBOSE" ]] && set -x
(
  cx in stats-data.csv // -h // parse // stats salary // md;
  echo $! > exit_code
) 2> stderr > actual
[[ -f expected ]] || cp actual expected
diff -u expected actual | (read _; read _; cat) > diff
[[ ! -s diff ]]
