#!/usr/bin/env bash
dir='ex/cmd/gnuplot-out/62a3ca6471f942c6cddee7aa4fbab515'
cp -p ex/data/*.* "$dir"
export CX_RANDOM_SEED=1638854222
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_EX_VERBOSE" ]] && set -x
cx in plot.csv // -h // gnuplot- --size=80x25 --style=b x // cmd gnuplot 2> stderr > actual
echo $! > exit_code
[[ -f expected ]] || cp actual expected
diff -u expected actual | (read _; read _; cat) > diff
[[ ! -s diff ]]
