#!/usr/bin/env bash
dir='ex/cmd/cut/b52a288dcedb5747b63340ccb022abdb'
cp -p ex/data/*.* "$dir"
export CX_RANDOM_SEED=1638854222
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_EX_VERBOSE" ]] && set -x
cx in SOME.csv // -h // cut '*,b:-' // h- 2> stderr > actual
echo $! > exit_code
[[ -f expected ]] || cp actual expected
diff -u expected actual | (read _; read _; cat) > diff
[[ ! -s diff ]]
