#!/usr/bin/env ruby
# frozen_string_literal: true

# "cx --help" for documentation.
# "cx ---test---" to execute integration tests.

$cx_t0 = Time.now

begin
  require 'set'
  needs_pry = %w(--verbose --debug ---pry--- ---test--- ---break---)
  unless Set.new(needs_pry).intersection(ARGV).empty?
    require 'pry'
  else
    $VERBOSE = nil
  end
end

require 'bundler/setup' unless ARGV.delete('---no-bundler---')
$:.unshift(File.expand_path('../../lib', __FILE__))

require 'cx/main'
exit CX::Main.new(ARGV).run!.exit_code
