#!/usr/bin/env ruby
# frozen_string_literal: true

# "cx --help" for documentation.
# "cx ---test---" to execute integration tests.

$cx_t0 = Time.now
$require_pry =
  %w(--verbose --debug ---pry--- ---test--- ---break---) & ARGV != []  
$VERBOSE = nil unless ARGV.include?("--debug")

require 'bundler/setup' unless ARGV.delete('---no-bundler---')
$:.unshift(File.expand_path('../../lib', __FILE__))
require 'pry' if $require_pry

require 'cx/main'
exit CX::Main.new(ARGV).run!.exit_code
