#!/usr/bin/env bash
dir='ex/cmd/edn-in/6353b5164461aefe549d7ce1b9954e99'
cp -p ex/data/*.* "$dir"
export CX_RANDOM_SEED=1638854222
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_VERBOSE" ]] && set -x
(
  cx in SOME.edn // -edn // h-;
  echo $! > exit_code
) 2> stderr > actual
[[ -f expected ]] || cp actual expected
diff -u expected actual | (read _; read _; cat) > diff
[[ ! -s diff ]]
