#!/usr/bin/env bash
dir='ex/cmd/cut/87e60097c8150295ce031bc857971e71'
cp -p ex/data/*.* "$dir"
cd "$dir" || exit 9
set -x
(
  cx in SOME.csv // -h // cut @,b:-  // h-
) >actual
echo $! > exit
[[ -f expected ]] || cp actual expected
diff -u expected actual | tee diff
[[ ! -s diff ]]
