#!/usr/bin/env bash
dir='ex/cmd/grep/17a312d16cc199d1a42157615fffd1ee'
cp -p ex/data/*.* "$dir"
PATH="$(/bin/pwd)/bin:$PATH"
cd "$dir" || exit 9
[[ -n "$CX_VERBOSE" ]] && set -x
(
  cx in SOME.csv // -h // grep d:f
) >actual
echo $! > exit
[[ -f expected ]] || cp actual expected
diff -u expected actual > diff
[[ ! -s diff ]]
